### create a question

POST http://127.0.0.1:5000/api/questions
Content-Type: application/json

{
    "name":"Todd",
    "text": "Todd has another question.",
    "repo": "repo",
    "live": "live"
}

### view question
GET http://127.0.0.1:5000/api/questions
Content-Type: application/json


### edit question

PATCH http://127.0.0.1:5000/api/questions/607652d23cbed73b8204e54e
Content-Type: application/json

{
    "name":"Todd",
    "text": "Todd has a test.",
    "repo": "repo",
    "live": "live",
    "answered":"true"
}

### delete question
DELETE http://127.0.0.1:5000/api/questions/606f5418b3acb61044c497d7
Content-Type: application/json
